### ISSUE TITLE
`baixa_img_audio` deveria soltar uma lista de responses mesmo?

### ISSUE THREAD

**Issue by jtrecenti** [decryptr/captchaReceitaAudio#1]
talvez seja mais intuitivo carregar o array da img e do audio já em `baixa_img_audio`.

**Comment by Athospd** [comment]
O motivo de retornar uma lista de response eh pq a ideia era tornar o site como um parâmetro (ex. consulta_cnpj) para q fosse possível fazer um POST posteriormente pra fazer alguma consulta no site da receita.
